import User from "./user.js";
import mongoose from "mongoose";
import bcrypt from "bcrypt";

const mockUsers = [
  // User
  {
    authorisationRole: "user",
    firstName: "Max",
    lastName: "Mustermann",
    addressDetails: {
      street: "Musterstraße",
      houseNumber: "123",
      postcode: "12345",
      city: "Musterstadt",
    },
    contactDetails: {
      phoneNumber: "0123456789",
      onCall: false,
      onCallPhoneNumber: "",
    },
    userName: "user",
    password: "testtest",
    employedSince: new Date("2020-01-01"),
    birthday: new Date("1990-01-01"),
    department: "Warehouse",
  },
  {
    authorisationRole: "user",
    firstName: "Erika",
    lastName: "Musterfrau",
    addressDetails: {
      street: "Musterweg",
      houseNumber: "456",
      postcode: "54321",
      city: "Musterdorf",
    },
    contactDetails: {
      phoneNumber: "9876543210",
      onCall: false,
      onCallPhoneNumber: "",
    },
    userName: "user2",
    password: "testtest",
    employedSince: new Date("2019-01-01"),
    birthday: new Date("1995-01-01"),
    department: "Logistics",
  },
  {
    authorisationRole: "user",
    firstName: "Hans",
    lastName: "Müller",
    addressDetails: {
      street: "Müllerstraße",
      houseNumber: "789",
      postcode: "98765",
      city: "Müllerdorf",
    },
    contactDetails: {
      phoneNumber: "2468135790",
      onCall: false,
      onCallPhoneNumber: "0667985354",
    },
    userName: "user3",
    password: "testtest",
    employedSince: new Date("2018-01-01"),
    birthday: new Date("1997-01-01"),
    department: "Account Management",
  },
  // Manager
  {
    authorisationRole: "manager",
    firstName: "Anna",
    lastName: "Beispiel",
    addressDetails: {
      street: "Beispielweg",
      houseNumber: "10a",
      postcode: "67890",
      city: "Beispielstadt",
    },
    contactDetails: {
      phoneNumber: "9876543210",
      onCall: true,
      onCallPhoneNumber: "1122334455",
    },
    userName: "manager",
    password: "testtest",
    employedSince: new Date("2018-06-15"),
    birthday: new Date("1985-05-15"),
    department: "Accounting",
  },
  {
    authorisationRole: "manager",
    firstName: "Hans",
    lastName: "Müller",
    addressDetails: {
      street: "Müllerstraße",
      houseNumber: "456",
      postcode: "54321",
      city: "Müllerdorf",
    },
    contactDetails: {
      phoneNumber: "1357924680",
      onCall: true,
      onCallPhoneNumber: "998877665544",
    },
    userName: "manager2",
    password: "testtest",
    employedSince: new Date("2016-09-01"),
    birthday: new Date("1982-10-01"),
    department: "Warehouse",
  },
  {
    authorisationRole: "manager",
    firstName: "Lisa",
    lastName: "Schulze",
    addressDetails: {
      street: "Schulstraße",
      houseNumber: "789",
      postcode: "98765",
      city: "Schulstadt",
    },
    contactDetails: {
      phoneNumber: "2468135790",
      onCall: true,
      onCallPhoneNumber: "998877665544",
    },
    userName: "manager3",
    password: "testtest",
    employedSince: new Date("2017-12-01"),
    birthday: new Date("1987-03-01"),
    department: "Logistics",
  },
  // Admin
  {
    authorisationRole: "admin",
    firstName: "John",
    lastName: "Doe",
    addressDetails: {
      street: "Adminstraße",
      houseNumber: "78",
      postcode: "54321",
      city: "Admindorf",
    },
    contactDetails: {
      phoneNumber: "1357924680",
      onCall: true,
      onCallPhoneNumber: "877887788778",
    },
    userName: "admin",
    password: "testtest",
    employedSince: new Date("2015-03-01"),
    birthday: new Date("1980-12-31"),
    department: "IT",
  },
  {
    authorisationRole: "admin",
    firstName: "Jane",
    lastName: "Doe",
    addressDetails: {
      street: "Adminstraße",
      houseNumber: "78",
      postcode: "54321",
      city: "Admindorf",
    },
    contactDetails: {
      phoneNumber: "1357924680",
      onCall: true,
      onCallPhoneNumber: "4444666600440",
    },
    userName: "admin2",
    password: "testtest",
    employedSince: new Date("2016-01-01"),
    birthday: new Date("1982-01-01"),
    department: "IT",
  },
  {
    authorisationRole: "admin",
    firstName: "Karl",
    lastName: "Black",
    addressDetails: {
      street: "Blackstraße",
      houseNumber: "78",
      postcode: "54321",
      city: "Beispielstadt",
    },
    contactDetails: {
      phoneNumber: "1357924680",
      onCall: true,
      onCallPhoneNumber: "998877665544",
    },
    userName: "admin3",
    password: "testtest",
    employedSince: new Date("2017-01-01"),
    birthday: new Date("1987-01-01"),
    department: "IT",
  },
  // Additional users for Warehouse department
  {
    authorisationRole: "user",
    firstName: "Klaus",
    lastName: "Weber",
    addressDetails: {
      street: "Lagerstraße",
      houseNumber: "22",
      postcode: "34567",
      city: "Lagerhausen",
    },
    contactDetails: {
      phoneNumber: "0123987654",
      onCall: false,
      onCallPhoneNumber: "",
    },
    userName: "user4",
    password: "testtest",
    employedSince: new Date("2021-03-15"),
    birthday: new Date("1993-07-20"),
    department: "Warehouse",
  },

  // Additional user for Logistics department
  {
    authorisationRole: "user",
    firstName: "Sophie",
    lastName: "Schmidt",
    addressDetails: {
      street: "Logistikweg",
      houseNumber: "8",
      postcode: "76543",
      city: "Logistikstadt",
    },
    contactDetails: {
      phoneNumber: "0987654321",
      onCall: false,
      onCallPhoneNumber: "",
    },
    userName: "user5",
    password: "testtest",
    employedSince: new Date("2022-01-10"),
    birthday: new Date("1991-11-05"),
    department: "Logistics",
  },

  // Additional users for Account Management department
  {
    authorisationRole: "user",
    firstName: "Julia",
    lastName: "Fischer",
    addressDetails: {
      street: "Kundenallee",
      houseNumber: "15",
      postcode: "23456",
      city: "Kundenhausen",
    },
    contactDetails: {
      phoneNumber: "0123456789",
      onCall: false,
      onCallPhoneNumber: "",
    },
    userName: "user6",
    password: "testtest",
    employedSince: new Date("2021-09-01"),
    birthday: new Date("1994-03-25"),
    department: "Account Management",
  },
  {
    authorisationRole: "supervisor",
    firstName: "Thomas",
    lastName: "Becker",
    addressDetails: {
      street: "Serviceweg",
      houseNumber: "3",
      postcode: "87654",
      city: "Servicehausen",
    },
    contactDetails: {
      phoneNumber: "9876543210",
      onCall: false,
      onCallPhoneNumber: "",
    },
    userName: "supervisor3",
    password: "testtest",
    employedSince: new Date("2023-02-15"),
    birthday: new Date("1992-09-10"),
    department: "Account Management",
  },

  // Additional users for Accounting department
  {
    authorisationRole: "supervisor",
    firstName: "Maria",
    lastName: "Schneider",
    addressDetails: {
      street: "Buchhaltungsstraße",
      houseNumber: "7",
      postcode: "45678",
      city: "Rechnungsstadt",
    },
    contactDetails: {
      phoneNumber: "0123789456",
      onCall: false,
      onCallPhoneNumber: "",
    },
    userName: "supervisor2",
    password: "testtest",
    employedSince: new Date("2022-07-01"),
    birthday: new Date("1990-05-15"),
    department: "Accounting",
  },
  {
    authorisationRole: "supervisor",
    firstName: "Peter",
    lastName: "Koch",
    addressDetails: {
      street: "Bilanzweg",
      houseNumber: "12",
      postcode: "56789",
      city: "Bilanzhausen",
    },
    contactDetails: {
      phoneNumber: "9876123450",
      onCall: false,
      onCallPhoneNumber: "",
    },
    userName: "supervisor1",
    password: "testtest",
    employedSince: new Date("2023-01-15"),
    birthday: new Date("1988-12-20"),
    department: "Accounting",
  },

  // Additional users for IT department
  {
    authorisationRole: "supervisor",
    firstName: "Laura",
    lastName: "Meyer",
    addressDetails: {
      street: "Serverstraße",
      houseNumber: "42",
      postcode: "98765",
      city: "Techstadt",
    },
    contactDetails: {
      phoneNumber: "0123456789",
      onCall: false,
      onCallPhoneNumber: "",
    },
    userName: "supervisor",
    password: "testtest",
    employedSince: new Date("2022-11-01"),
    birthday: new Date("1995-08-30"),
    department: "IT",
  },
  {
    authorisationRole: "user",
    firstName: "Michael",
    lastName: "Wagner",
    addressDetails: {
      street: "Codeweg",
      houseNumber: "101",
      postcode: "34567",
      city: "Programmierhausen",
    },
    contactDetails: {
      phoneNumber: "9876543210",
      onCall: false,
      onCallPhoneNumber: "",
    },
    userName: "user11",
    password: "testtest",
    employedSince: new Date("2023-03-15"),
    birthday: new Date("1993-02-14"),
    department: "IT",
  },
  {
    authorisationRole: "user",
    firstName: "Anna",
    lastName: "Schmidt",
    addressDetails: {
      street: "Buchhaltergasse",
      houseNumber: "42",
      postcode: "60323",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069123456",
      onCall: true,
      onCallPhoneNumber: "0171987654",
    },
    userName: "userextra1",
    password: "sicher123!",
    employedSince: new Date("2019-03-15"),
    birthday: new Date("1990-05-20"),
    department: "Accounting",
  },
  {
    authorisationRole: "user",
    firstName: "Markus",
    lastName: "Weber",
    addressDetails: {
      street: "Bilanzweg",
      houseNumber: "7",
      postcode: "60486",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069876543",
      onCall: false,
      onCallPhoneNumber: "0162345678",
    },
    userName: "userextra2",
    password: "buchhaltung2023",
    employedSince: new Date("2020-09-01"),
    birthday: new Date("1985-11-30"),
    department: "Accounting",
  },
  {
    authorisationRole: "user",
    firstName: "Simone",
    lastName: "Becker",
    addressDetails: {
      street: "Kontenallee",
      houseNumber: "15",
      postcode: "60325",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069246810",
      onCall: true,
      onCallPhoneNumber: "0177654321",
    },
    userName: "userextra3",
    password: "zahlen&daten!",
    employedSince: new Date("2017-06-01"),
    birthday: new Date("1988-08-12"),
    department: "Accounting",
  },
  //logistics manager
  {
    authorisationRole: "manager",
    firstName: "Petra",
    lastName: "Schulze",
    addressDetails: {
      street: "Logistikweg",
      houseNumber: "42",
      postcode: "60306",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069123456",
      onCall: true,
      onCallPhoneNumber: "0171987654",
    },
    userName: "userlogistics1",
    password: "test123!",
    employedSince: new Date("2017-12-01"),
    birthday: new Date("1987-03-01"),
    department: "Logistics",
  },
  {
    authorisationRole: "manager",
    firstName: "Michael",
    lastName: "Koch",
    addressDetails: {
      street: "Lagerstrasse",
      houseNumber: "7",
      postcode: "60486",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069876543",
      onCall: false,
      onCallPhoneNumber: "0162345678",
    },
    userName: "userlogistics2",
    password: "lager2023",
    employedSince: new Date("2019-09-01"),
    birthday: new Date("1985-11-30"),
    department: "Logistics",
  },
  {
    authorisationRole: "manager",
    firstName: "Sandra",
    lastName: "BuchMüller",
    addressDetails: {
      street: "Warenweg",
      houseNumber: "15",
      postcode: "60325",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069246810",
      onCall: true,
      onCallPhoneNumber: "0177654321",
    },
    userName: "userlogistics3",
    password: "waren&daten!",
    employedSince: new Date("2018-06-01"),
    birthday: new Date("1988-08-12"),
    department: "Logistics",
  },
  //warehouse manager
  {
    authorisationRole: "manager",
    firstName: "Tom",
    lastName: "Hans",
    addressDetails: {
      street: "Lagerweg",
      houseNumber: "42",
      postcode: "60306",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069123456",
      onCall: true,
      onCallPhoneNumber: "0171987654",
    },
    userName: "userwarehouse1",
    password: "test123!",
    employedSince: new Date("2017-12-01"),
    birthday: new Date("1987-03-01"),
    department: "Warehouse",
  },
  {
    authorisationRole: "manager",
    firstName: "Michael",
    lastName: "Schmitz",
    addressDetails: {
      street: "Lagerstrasse",
      houseNumber: "7",
      postcode: "60486",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069876543",
      onCall: false,
      onCallPhoneNumber: "0162345678",
    },
    userName: "userwarehouse2",
    password: "lager2023",
    employedSince: new Date("2019-09-01"),
    birthday: new Date("1985-11-30"),
    department: "Warehouse",
  },
  {
    authorisationRole: "manager",
    firstName: "Bianka",
    lastName: "Busch",
    addressDetails: {
      street: "Warenweg",
      houseNumber: "15",
      postcode: "60325",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069246810",
      onCall: true,
      onCallPhoneNumber: "0177654321",
    },
    userName: "userwarehouse3",
    password: "waren&daten!",
    employedSince: new Date("2018-06-01"),
    birthday: new Date("1988-08-12"),
    department: "Warehouse",
  },
  //accounting manager
  {
    authorisationRole: "manager",
    firstName: "Anna",
    lastName: "Schmidt",
    addressDetails: {
      street: "Buchhalter, 42",
      houseNumber: "42",
      postcode: "60323",
      city: "Friesland",
    },
    contactDetails: {
      phoneNumber: "069123456",
      onCall: true,
      onCallPhoneNumber: "01719876555",
    },
    userName: "useraccounting1",
    password: "sicher123!",
    employedSince: new Date("2019-03-15"),
    birthday: new Date("1990-05-20"),
    department: "Accounting",
  },
  {
    authorisationRole: "manager",
    firstName: "Markus",
    lastName: "Wiegand",
    addressDetails: {
      street: "Bilanzweg",
      houseNumber: "7",
      postcode: "60486",
      city: "Friestadt",
    },
    contactDetails: {
      phoneNumber: "069876543",
      onCall: false,
      onCallPhoneNumber: "0162345678",
    },
    userName: "useraccounting2",
    password: "buchhaltung2023",
    employedSince: new Date("2020-09-01"),
    birthday: new Date("1985-11-30"),
    department: "Accounting",
  },
  {
    authorisationRole: "manager",
    firstName: "Anna-Kathrin",
    lastName: "Peters",
    addressDetails: {
      street: "Kontenallee",
      houseNumber: "15",
      postcode: "60325",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069246810",
      onCall: true,
      onCallPhoneNumber: "0177654321",
    },
    userName: "useraccounting3",
    password: "zahlen&daten!",
    employedSince: new Date("2017-06-01"),
    birthday: new Date("1988-08-12"),
    department: "Accounting",
  },
  //IT manager
  {
    authorisationRole: "manager",
    firstName: "Manuel",
    lastName: "Tisch",
    addressDetails: {
      street: "IT-Weg",
      houseNumber: "42",
      postcode: "60306",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069123456",
      onCall: true,
      onCallPhoneNumber: "0171987654",
    },
    userName: "userit1",
    password: "test123!",
    employedSince: new Date("2017-12-01"),
    birthday: new Date("1987-03-01"),
    department: "IT",
  },
  {
    authorisationRole: "manager",
    firstName: "Klaus",
    lastName: "Weigert",
    addressDetails: {
      street: "ITstrasse",
      houseNumber: "7",
      postcode: "60486",
      city: "Berlin",
    },
    contactDetails: {
      phoneNumber: "069876543",
      onCall: false,
      onCallPhoneNumber: "0162345678",
    },
    userName: "userit2",
    password: "lager2023",
    employedSince: new Date("2019-09-01"),
    birthday: new Date("1985-11-30"),
    department: "IT",
  },

  {
    authorisationRole: "manager",
    firstName: "Melanie",
    lastName: "Bauer",
    addressDetails: {
      street: "Warenweg",
      houseNumber: "15",
      postcode: "60325",
      city: "Wiesbaden",
    },
    contactDetails: {
      phoneNumber: "069246810",
      onCall: true,
      onCallPhoneNumber: "0177654321",
    },
    userName: "userit3",
    password: "waren&daten!",
    employedSince: new Date("2018-06-01"),
    birthday: new Date("1988-08-12"),
    department: "IT",
  },
  //manager Accounting
  {
    authorisationRole: "manager",
    firstName: "Anna",
    lastName: "Hablitz",
    addressDetails: {
      street: "Buchhaltergasse",
      houseNumber: "42",
      postcode: "60323",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069123456",
      onCall: true,
      onCallPhoneNumber: "01719876098",
    },
    userName: "manageraccounting",
    password: "sicher123!",
    employedSince: new Date("2019-03-15"),
    birthday: new Date("1990-05-20"),
    department: "Accounting",
  },
  //Supervisor logistics
  {
    authorisationRole: "supervisor",
    firstName: "Thomas",
    lastName: "Anders",
    addressDetails: {
      street: "Lagerweg",
      houseNumber: "42",
      postcode: "60306",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069123456",
      onCall: true,
      onCallPhoneNumber: "0171987654",
    },
    userName: "supervisorlogistics1",
    password: "test123!",
    employedSince: new Date("2017-12-01"),
    birthday: new Date("1987-03-01"),
    department: "Logistics",
  },
  {
    authorisationRole: "supervisor",
    firstName: "Christian",
    lastName: "Lange",
    addressDetails: {
      street: "Lagerstrasse",
      houseNumber: "7",
      postcode: "60486",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069876543",
      onCall: false,
      onCallPhoneNumber: "0162345678",
    },
    userName: "supervisorlogistics2",
    password: "lager2023",
    employedSince: new Date("2019-09-01"),
    birthday: new Date("1985-11-30"),
    department: "Logistics",
  },
  {
    authorisationRole: "supervisor",
    firstName: "Nadine",
    lastName: "Ullrich",
    addressDetails: {
      street: "Warenweg",
      houseNumber: "15",
      postcode: "60325",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069246810",
      onCall: true,
      onCallPhoneNumber: "0177654321",
    },
    userName: "supervisorlogistics3",
    password: "waren&daten!",
    employedSince: new Date("2018-06-01"),
    birthday: new Date("1988-08-12"),
    department: "Logistics",
  },
  //supervisor warehouse
  {
    authorisationRole: "supervisor",
    firstName: "Tom",
    lastName: "Hans",
    addressDetails: {
      street: "Lagerweg",
      houseNumber: "42",
      postcode: "60306",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069123456",
      onCall: true,
      onCallPhoneNumber: "0171987654",
    },
    userName: "supervisorwarehouse1",
    password: "test123!",
    employedSince: new Date("2017-12-01"),
    birthday: new Date("1987-03-01"),
    department: "Warehouse",
  },
  {
    authorisationRole: "supervisor",
    firstName: "Daniel",
    lastName: "Schmidt",
    addressDetails: {
      street: "Lagerstrasse",
      houseNumber: "7",
      postcode: "60486",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069876543",
      onCall: false,
      onCallPhoneNumber: "0162345678",
    },
    userName: "supervisorwarehouse2",
    password: "lager2023",
    employedSince: new Date("2019-09-01"),
    birthday: new Date("1985-11-30"),
    department: "Warehouse",
  },
  {
    authorisationRole: "supervisor",
    firstName: "Nina",
    lastName: "Vogel",
    addressDetails: {
      street: "Warenweg",
      houseNumber: "15",
      postcode: "60325",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069246810",
      onCall: true,
      onCallPhoneNumber: "0177654321",
    },
    userName: "supervisorwarehouse3",
    password: "waren&daten!",
    employedSince: new Date("2018-06-01"),
    birthday: new Date("1988-08-12"),
    department: "Warehouse",
  },
  //supervisor accounting
  {
    authorisationRole: "supervisor",
    firstName: "Anna",
    lastName: "Schmidt",
    addressDetails: {
      street: "Buchhalter, 42",
      houseNumber: "142",
      postcode: "60323",
      city: "Friesland",
    },
    contactDetails: {
      phoneNumber: "069123456",
      onCall: true,
      onCallPhoneNumber: "0171987634",
    },
    userName: "supervisoraccounting1",
    password: "sicher123!",
    employedSince: new Date("2019-03-15"),
    birthday: new Date("1990-05-20"),
    department: "Accounting",
  },
  {
    authorisationRole: "supervisor",
    firstName: "Markus",
    lastName: "Wiegand",
    addressDetails: {
      street: "Steuerweg",
      houseNumber: "7",
      postcode: "60486",
      city: "Friestadt",
    },
    contactDetails: {
      phoneNumber: "069876543",
      onCall: false,
      onCallPhoneNumber: "0162345678",
    },
    userName: "supervisoraccounting2",
    password: "buchhaltung2023",
    employedSince: new Date("2020-09-01"),
    birthday: new Date("1985-11-30"),
    department: "Accounting",
  },
  {
    authorisationRole: "supervisor",
    firstName: "Christina-Angela",
    lastName: "Jäger",
    addressDetails: {
      street: "Kontenallee",
      houseNumber: "15",
      postcode: "60325",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069246810",
      onCall: true,
      onCallPhoneNumber: "0177654321",
    },
    userName: "supervisoraccounting3",
    password: "zahlen&daten!",
    employedSince: new Date("2017-06-01"),
    birthday: new Date("1988-08-12"),
    department: "Accounting",
  },
  //supervisor IT
  {
    authorisationRole: "supervisor",
    firstName: "Lars",
    lastName: "Tisch",
    addressDetails: {
      street: "IT-Weg",
      houseNumber: "42",
      postcode: "60306",
      city: "Frankfurt",
    },
    contactDetails: {
      phoneNumber: "069123456",
      onCall: true,
      onCallPhoneNumber: "0171987654",
    },
    userName: "supervisorit1",
    password: "test123!",
    employedSince: new Date("2017-12-01"),
    birthday: new Date("1987-03-01"),
    department: "IT",
  },
  {
    authorisationRole: "supervisor",
    firstName: "Klaus",
    lastName: "Weigert",
    addressDetails: {
      street: "ITstrasse",
      houseNumber: "7",
      postcode: "60486",
      city: "Berlin",
    },
    contactDetails: {
      phoneNumber: "069876543",
      onCall: false,
      onCallPhoneNumber: "0162345678",
    },
    userName: "supervisorit2",
    password: "lager2023",
    employedSince: new Date("2019-09-01"),
    birthday: new Date("1985-11-30"),
    department: "IT",
  },
  {
    authorisationRole: "supervisor",
    firstName: "Melanie",
    lastName: "Bauer",
    addressDetails: {
      street: "Warenweg",
      houseNumber: "15",
      postcode: "60325",
      city: "Wiesbaden",
    },
    contactDetails: {
      phoneNumber: "069246810",
      onCall: true,
      onCallPhoneNumber: "0177654321",
    },
    userName: "supervisorit3",
    password: "waren&daten!",
    employedSince: new Date("2018-06-01"),
    birthday: new Date("1988-08-12"),
    department: "IT",
  },
];

async function createMockUsers() {
  try {
    await mongoose.connect("mongodb://localhost:27017/storage");
    // delete existing data
    await User.deleteMany({});

    for (const userData of mockUsers) {
      const salt = await bcrypt.genSalt(10);
      const hashedPassword = await bcrypt.hash(userData.password, salt);

      const user = new User({
        ...userData,
        password: hashedPassword,
      });

      await user.save();
      console.log(`Created user: ${user.firstName} ${user.lastName}`);
    }

    console.log("Mock data created successfully");
  } catch (err) {
    console.error("Error creating mock data:", err.message);
  } finally {
    mongoose.disconnect();
  }
}

createMockUsers();
